<?php

/**
 * Created by PhpStorm.
 * User: professor-taha
 * Date: 4/30/16
 * Time: 8:32 PM
 */
class Application_Form_Login extends Zend_Form
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->addElementPrefixPath(
            'Application_Validate',
            APPLICATION_PATH . '/models/validate/',
            'validate'
        );
        $element = $this->createElement('text', 'email', array(
            'label' => "Email",
            'required' => true,
            'validators' => ['EmailAddress'],
			'filters' => ['StringTrim', 'StringToLower'] 

        ));
        $this->addElement($element);
        $element = $this->createElement('password', 'password', array(
            'label' => "Password",
            'required' => true,
        ));
        $this->addElement($element);
        $element = $this->createElement('submit', 'submit', array(
            'label' => "Login",
            'required' => true,
        ));
        $this->addElement($element);
        $this -> addDecorator('formElements');
        $this -> addDecorator('htmlTag');
        $this -> addDecorator('formErrors');
        $this -> addDecorator('form');
        $this -> getDecorator('formErrors') -> setOption('placement','PREPEND');
        $this -> setAction('/User/authenticate');
        $this -> setMethod('post');
    }

}