<?php

/**
 * Created by PhpStorm.
 * User: professor-taha
 * Date: 4/30/16
 * Time: 8:32 PM
 */
class Application_Form_Login extends Application_Form_Abstract
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->addElementPrefixPath(
            'Application_Validate',
            APPLICATION_PATH . '/models/validate/',
            'validate'
        );
        $element = $this->createElement('text', 'email', array(
            'label' => "Email",
            'required' => true,
            'validators' => ['EmailAddress'],
			'filters' => ['StringTrim', 'StringToLower'],
			'helper' => 'formEmail',
			'class' => 'form-control'

        ));
        $this->addElement($element);
        $element = $this->createElement('password', 'password', array(
            'label' => "Password",
            'required' => true,
			'class' => 'form-control'
        ));
        $this->addElement($element);
        $element = $this->createElement('submit', 'submit', array(
            'label' => "Login",
            'required' => true,
			'class' => 'btn btn-primary btn-block',
        ));
		$element -> getDecorator('first')->setOption('class',  'col-xs-offset-3 col-xs-8 col-sm-4');
		$element -> removeDecorator('Label'); 
        $this->addElement($element);
        $this -> setAction('/User/authenticate');
        $this -> setMethod('post');
    }

}